@c Copyright (C) 1988, 1989, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
@c 1999, 2000, 2001, 2002 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.

@node 配置文件
@subsubsection 由@code{configure}创建的文件

我们在这里说明了在@file{gcc}目录下哪些文件将会由@file{configure}创建。
其它一些文件是在配置过程中生成的临时文件，而且在后续的构建过程中没有被用到，
就不在这里介绍了。

@itemize @bullet
@item
@file{Makefile}是由@file{Makefile.in}、@file{config}目录下的主机与目标机片断
（@pxref{片段, , Makefile片段}）@file{t-@var{target}}和
@file{x-@var{host}}共同构造出来的，根据情况可能还会用到Makefile语言片断
@file{@var{language}/Make-lang.in}。
@item
@file{auto-host.h}包含了由@file{configure}确定的主机信息。
如果主机和构建机不同，则@file{suto-build.h}也会被创建，
其包含了关于构建机的信息。
@item
@file{config.status}脚本，可以用来运行并重新创建当前配置。
@item
@file{configargs.h}头文件，包含了传给@file{configure}来配置GCC的详细参数，
以及使用的线程模式。
@item
@file{cstamp-h}作为时间戳使用。
@item
@file{fixinc/Makefile}由@file{fixinc/Makefile.in}创建。
@item
@file{gccbug}, 用来报告GCC bugs的脚本，由@file{gccbug.in}创建。
@item
@file{intl/Makefile}由@file{intl/Makefile.in}创建。
@item
如果语言相关的@file{config-lang.in}文件
（@pxref{前端配置, ,The Front End @file{config-lang.in} File}）
设置了@code{outputs}，则在@code{outputs}中列出的文件也会被创建。
@end itemize

下列配置头文件是由Makefile通过使用@file{mkconfig.sh}，
而不是直接通过@file{configure}来创建的。
@file{config.h}，@file{bconfig.h}和@file{tconfig.h}都包含
@file{xm-@var{machine}.h}头文件，如果存在的话，
分别对应于host, build和target机器。
对于target，是一些配置头文件和一些定义；
对于host和build机器，这些包括由@file{configure}生成的自动配置头文件。
其它配置头文件由@file{config.gcc}来确定。
它们也包含@code{rtx}，@code{rtvec}和@code{tree}的typedef定义。

@itemize @bullet
@item
@file{config.h}, 供运行在host机器上的程序使用。 
@item
@file{bconfig.h}, 供运行在build机器上的程序使用。
@item
@file{tconfig.h}, 供运行在target机器上的程序和库使用。
@item
@file{tm_p.h}, 包括了含有target机器上@file{.c}
文件中的函数原形的头文件@file{@var{machine}-protos.h}。
FIXME：为什么需要这样一个独立的头文件？
@end itemize
