@c Copyright (C) 1988, 1989, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
@c 1999, 2000, 2001, 2004, 2006 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.

@en @node Contributing
@en @chapter Contributing to GCC Development
@node 贡献
@chapter 向GCC开发提供帮助

@en If you would like to help pretest GCC releases to assure they work well,
@en current development sources are available by SVN (see
@en @uref{http://gcc.gnu.org/svn.html}).  Source and binary snapshots are
@en also available for FTP; see @uref{http://gcc.gnu.org/snapshots.html}.
如果你愿意帮助预测试GCC发行版，以确保它们正常工作，则可以通过SVN (参见
@uref{http://gcc.gnu.org/svn.html}) 来获得当前的开发源码。源代码和二进制
程序的快照也可以从FTP上获得（参见 @uref{http://gcc.gnu.org/snapshots.html}）。

@en If you would like to work on improvements to GCC, please read the
@en advice at these URLs:
如果你愿意从事改进GCC的工作，请阅读这些链接上的建议：

@smallexample
@uref{http://gcc.gnu.org/contribute.html}
@uref{http://gcc.gnu.org/contributewhy.html}
@end smallexample

@noindent
@en for information on how to make useful contributions and avoid
@en duplication of effort.  Suggested projects are listed at
@en @uref{http://gcc.gnu.org/projects/}.
上面给出了如何提供有益帮助以及如何避免重复工作的信息。在@uref{http://gcc.gnu.org/projects/}上列出了被推荐的项目。
