@c Copyright (C) 1988, 1989, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
@c 1999, 2000, 2001, 2004, 2006 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.

@node Contributing
@chapter 向GCC开发提供帮助

如果你愿意帮助预测试GCC发行版，以确保它们可以正常工作，可以通过SVN (see
@uref{http://gcc.gnu.org/svn.html}) 来获得开发源代码。源代码和二进制程序的快照也可以从FTP上得到（see @uref{http://gcc.gnu.org/snapshots.html}）。

如果你愿意从事改进GCC的工作，请阅读这些链接上的建议：

@smallexample
@uref{http://gcc.gnu.org/contribute.html}
@uref{http://gcc.gnu.org/contributewhy.html}
@end smallexample

@noindent
有关如何提供好的帮助以及如何避免重复工作，在
@uref{http://gcc.gnu.org/projects/}上列出了推建的项目。
