@c Copyright (C) 2010

@node Translation Contributors
@unnumbered 为翻译GCC Internals作出过贡献的人

感谢大家参与GCC Internals中文翻译项目（http://code.google.com/p/gccint-zh）。如果你对该项目感兴趣，或者下面的列表中遗漏了你的信息，欢迎跟我联系（mingjie.xing AT gmail.com）。按照姓氏拼音排序：

@itemize @bullet

@item Jingyi Hou	<houjingyi AT gmail.com>
@item Xinping Huang	<xinping.huang AT gmail.com>
@item J L		<proljc AT gmail.com>
@item Yao Qi		<qiyaoltc AT gmail.com>
@item Wei Wu		<wuwei.gucas AT gmail.com>
@item Mingjie Xing	<mingjie.xing AT gmail.com>

@end itemize

