@c Copyright (C) 2010

@node Translation Contributors
@unnumbered 为翻译GCC Internals作出过贡献的人

感谢大家参与GCC Internals中文翻译项目（http://code.google.com/p/gccint-zh）。如果你对该项目感兴趣，或者下面的列表中遗漏了你的信息，欢迎跟我联系（mingjie.xing AT gmail.com）。按照姓氏（姓在前面，名在后面）拼音排序：

@itemize @bullet

@item Chen Wei Ren	<chenwj AT iis.sinica.edu.tw>
@item Ding Cong		<tuxding AT gmail.com>
@item Hou Jingyi	<houjingyi AT gmail.com>
@item Huang Xinping	<xinping.huang AT gmail.com>
@item Liu Jia		<proljc AT gmail.com>
@item Qi Yao		<qiyaoltc AT gmail.com>
@item Tianguau          <tianguau AT gmail.com>
@item Wang Tao		<windaoo AT gmail.com>
@item Wu Wei		<wuwei.gucas AT gmail.com>
@item Xing Mingjie	<mingjie.xing AT gmail.com>


@end itemize

