\input texinfo  @c -*-texinfo-*-
@c %**start of header
@setfilename gccint.info
@documentlanguage zh_CN
@c INTERNALS is used by md.texi to determine whether to include the
@c whole of that file, in the internals manual, or only the part
@c dealing with constraints, in the user manual.
@set INTERNALS 

@c See miscellaneous notes in gcc.texi on checks/things to do.

@include gcc-common.texi

@settitle GNU Compiler Collection (GCC) Internals

@c Create a separate index for command line options.
@defcodeindex op
@c Merge the standard indexes into a single one.
@syncodeindex fn cp
@syncodeindex vr cp
@syncodeindex ky cp
@syncodeindex pg cp
@syncodeindex tp cp

@paragraphindent 1

@c %**end of header

@copying
@c Copyright @copyright{} 1988, 1989, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
@c 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
@c 2008, 2010 Free Software Foundation, Inc.
版权 @copyright{} 1988, 1989, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2010 自由软件基金会

@c Permission is granted to copy, distribute and/or modify this document
@c under the terms of the GNU Free Documentation License, Version 1.3 or
@c any later version published by the Free Software Foundation; with the
@c Invariant Sections being ``Funding Free Software'', the Front-Cover
@c Texts being (a) (see below), and with the Back-Cover Texts being (b)
@c (see below).  A copy of the license is included in the section entitled
@c ``GNU Free Documentation License''.
您可以依据自由软件基金会所发行的GNU自由文档授权1.3版本或者之后的任何版本，
对本文档进行复制，分发和/或修改；其中不可变章节为"资助自由软件"，封面文
字为 (a) (参见下面)，以及封底文字为 (b) (参见下面)。授权的副本要被包含在
标题为"GNU自由文档授权"的章节中。

@c (a) The FSF's Front-Cover Text is:
@c 
@c      A GNU Manual
@c 
@c (b) The FSF's Back-Cover Text is:
@c 
@c      You have freedom to copy and modify this GNU Manual, like GNU
@c      software.  Copies published by the Free Software Foundation raise
@c      funds for GNU development.
(a) FSF的封面文字为：

     GNU 手册

(b) FSF的封底文字为：

     您可以自由复制和修改本GNU手册，如同GNU软件。由自由软件基金会所发行
     的副本用于为GNU开发筹集资金。
@end copying
@ifnottex
@dircategory Software development
@direntry
* gccint: (gccint).            Internals of the GNU Compiler Collection.
@end direntry
@c This file documents the internals of the GNU compilers.
该文档介绍了GNU编译器的内部实现。
@sp 1
@insertcopying
@sp 1
@end ifnottex

@setchapternewpage odd
@titlepage
@title GNU Compiler Collection Internals
@versionsubtitle
@author Richard M. Stallman and the @sc{GCC} Developer Community
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@summarycontents
@contents
@page

@c @node Top, Contributing,, (DIR)
@c @top Introduction
@c @cindex introduction
@node Top, 贡献,, (DIR)
@top 简介
@cindex introduction

@c This manual documents the internals of the GNU compilers, including
@c how to port them to new targets and some information about how to
@c write front ends for new languages.  It corresponds to the compilers
该手册介绍了GNU编译器的内部实现，包括怎样移植到新的目标机上，
以及一些如何为新语言编写前端的信息。手册基于编译器（GCC）
@c @ifset VERSION_PACKAGE
@c @value{VERSION_PACKAGE}
@c @end ifset
@c version @value{version-GCC}.  The use of the GNU compilers is documented in a
@c separate manual.  @xref{Top,, Introduction, gcc, Using the GNU
@c Compiler Collection (GCC)}.
版本4.6.0。
GNU编译器的使用方法在另一个手册中介绍，参见 
@ref{Top,, Introduction, gcc, Using the GNU Compiler Collection (GCC)}。

@c This manual is mainly a reference manual rather than a tutorial.  It
@c discusses how to contribute to GCC (@pxref{Contributing}), the
@c characteristics of the machines supported by GCC as hosts and targets
@c (@pxref{Portability}), how GCC relates to the ABIs on such systems
@c (@pxref{Interface}), and the characteristics of the languages for
@c which GCC front ends are written (@pxref{Languages}).  It then
@c describes the GCC source tree structure and build system, some of the
@c interfaces to GCC front ends, and how support for a target system is
@c implemented in GCC@.
该手册主要是一个参考手册而不是教程。它讨论了如何帮助GCC (参见 @ref{贡献})，
GCC所支持的主机和目标机的机器特征 (参见 @ref{可移植性})，GCC与这些系统的ABI是
如何联系的 (参见 @ref{接口})，GCC前端所支持的语言特征 (参见 @ref{语言})。然后
描述了GCC源文件目录结构和构建系统，GCC前端的一些接口，以及GCC如何实现对目标系统
的支持。

@c Additional tutorial information is linked to from
@c @uref{http://gcc.gnu.org/readings.html}.
更多参考资料的链接在@uref{http://gcc.gnu.org/readings.html}上。

@c @menu
@c * Contributing::    How to contribute to testing and developing GCC.
@c * Portability::     Goals of GCC's portability features.
@c * Interface::       Function-call interface of GCC output.
@c * Libgcc::          Low-level runtime library used by GCC.
@c * Languages::       Languages for which GCC front ends are written.
@c * Source Tree::     GCC source tree structure and build system.
@c * Testsuites::      GCC testsuites.
@c * Options::         Option specification files.
@c * Passes::          Order of passes, what they do, and what each file is for.
@c * GENERIC::         Language-independent representation generated by Front Ends
@c * GIMPLE::          Tuple representation used by Tree SSA optimizers
@c * Tree SSA::        Analysis and optimization of GIMPLE
@c * RTL::             Machine-dependent low-level intermediate representation.
@c * Control Flow::    Maintaining and manipulating the control flow graph.
@c * Loop Analysis and Representation:: Analysis and representation of loops
@c * Machine Desc::    How to write machine description instruction patterns.
@c * Target Macros::   How to write the machine description C macros and functions.
@c * Host Config::     Writing the @file{xm-@var{machine}.h} file.
@c * Fragments::       Writing the @file{t-@var{target}} and @file{x-@var{host}} files.
@c * Collect2::        How @code{collect2} works; how it finds @code{ld}.
@c * Header Dirs::     Understanding the standard header file directories.
@c * Type Information:: GCC's memory management; generating type information.
@c * Plugins::         Extending the compiler with plugins.
@c 
@c * Funding::         How to help assure funding for free software.
@c * GNU Project::     The GNU Project and GNU/Linux.
@c 
@c * Copying::         GNU General Public License says
@c                     how you can copy and share GCC.
@c * GNU Free Documentation License:: How you can copy and share this manual.
@c * Contributors::    People who have contributed to GCC.
@c 
@c * Option Index::    Index to command line options.
@c * Concept Index::   Index of concepts and symbol names.
@c @end menu
@menu
* 贡献::            如何帮助测试和开发GCC。
* 可移植性::        GCC的可移植性。
* 接口::            GCC输出的函数调用接口。
* Libgcc::          GCC使用的低级运行时库。
* 语言::            GCC前端支持的语言。
* 源目录::          GCC源目录结构和构建系统。
* 测试包::          GCC测试包。
* 选项::            选项描述文件。
* Passes::          pass的顺序，它们做了什么，以及相关的源文件。
* RTL::             大多pass赖以工作的中间表示。
* GENERIC::         前端生成的语言无关的表示。
* GIMPLE::          Tree SSA优化器使用的元组表示。
* Tree SSA::        分析和优化GIMPLE
* 控制流::          维护和操作控制流图。
* 循环分析和表示::  对循环的分析和表示。
* 机器描述::        如何写机器描述指令模板。
* 目标宏::          如何写机器描述C宏和函数。
* 主机配置::        编写 @file{xm-@var{machine}.h} 文件。
* 片段::            编写 @file{t-@var{target}} 和 @file{x-@var{host}} 文件。
* Collect2::        @code{collect2} 是如何工作的; 如何找到 @code{ld}。
* 头文件目录::      理解标准头文件目录。
* 类型信息::        GCC的内存管理；生成类型信息。
* 插件::            使用插件来扩展编译器。
* 资助::            如何向自由软件提供资金帮助。
* GNU项目::         GNU项目和GNU/Linux。
* 版权::            GNU通用公共授权告诉你如何能够复制和分享GCC。
* GNU自由文档授权:: 如何能够复制和分享该手册。
* 贡献者::          向GCC作出过贡献的人。
* 选项索引::        命令行选项索引。
* 概念索引::        概念和符号名索引。
@end menu

@include contribute.texi
@include portability.texi
@include interface.texi
@include libgcc.texi
@include languages.texi
@include sourcebuild.texi
@include options.texi
@include passes.texi
@include rtl.texi
@include generic.texi
@include gimple.texi
@include tree-ssa.texi
@include loop.texi
@include cfg.texi
@include md.texi
@include tm.texi
@include hostconfig.texi
@include fragments.texi
@include collect2.texi
@include headerdirs.texi
@include gty.texi
@include plugins.texi

@include funding.texi
@include gnu.texi
@include gpl_v3.texi

@c ---------------------------------------------------------------------
@c GFDL
@c ---------------------------------------------------------------------

@include fdl.texi

@include contrib.texi

@c ---------------------------------------------------------------------
@c Indexes
@c ---------------------------------------------------------------------

@c @node Option Index
@c @unnumbered Option Index
@node 选项索引
@unnumbered 选项索引

GCC's command line options are indexed here without any initial @samp{-}
or @samp{--}.  Where an option has both positive and negative forms
(such as @option{-f@var{option}} and @option{-fno-@var{option}}),
relevant entries in the manual are indexed under the most appropriate
form; it may sometimes be useful to look up both forms.

@printindex op

@c @node Concept Index
@c @unnumbered Concept Index
@node 概念索引
@unnumbered 概念索引

@printindex cp

@c ---------------------------------------------------------------------
@c Epilogue
@c ---------------------------------------------------------------------

@bye
