@c Copyright (C) 2001 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.

@node GNU Project
@unnumbered The GNU Project and GNU/Linux

@en The GNU Project was launched in 1984 to develop a complete Unix-like
@en operating system which is free software: the GNU system.  (GNU is a
@en recursive acronym for ``GNU's Not Unix''; it is pronounced
@en ``guh-NEW''@.)  Variants of the GNU operating system, which use the
@en kernel Linux, are now widely used; though these systems are often
@en referred to as ``Linux'', they are more accurately called GNU/Linux
@en systems.
GNU 项目开始于 1984 年，以开发一个完整的类 Unix 操作系统自由软件，这个系统则是 GNU 系统。（ GNU 是 ``GNU's Not Unix'' 的递归缩写；它的发音是 ``ugh-NEW''）。很多 GNU 操作系统的变体都使用 linux 内核，并正被广泛地使用着。虽然这些系统通常被称为 ``Linux'' ，但更准确地说它们应该叫 GNU/Linux 系统。

@en For more information, see:
更多详细信息见：
@smallexample
@uref{http://www.gnu.org/}
@uref{http://www.gnu.org/gnu/linux-and-gnu.html}
@end smallexample
