@c Copyright (C) 1988, 1989, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.

@node 头文件目录
@chapter 标准头文件目录

@code{GCC_INCLUDE_DIR} 意味着对于本地和交叉都相同的。这是GCC存放私有
包含文件和修订过的（fixed）包含文件的地方。交叉编译的GCC会对 
@file{$(tooldir)/include} 下的头文件运行 @code{fixincludes}。（如果
交叉编译头文件需要被修订，它们必须在构建GCC之前安装。如果交叉编译头
文件已经适合GCC，则不需要任何特定修改。）

@file{GPLUSPLUS_INCLUDE_DIR} 意味着对于本地和交叉都相同的。这是 
@command{g++} 首先查找头文件的地方。C++库只安装目标独立的头文件到这
里。

@code{LOCAL_INCLUDE_DIR} 只被本地编译器使用，GCC并不安装任何文件到里
面。正常情况下为 @file{/usr/local/include}。这是系统放置额外头文件的
地方。

@code{CROSS_INCLUDE_DIR} 只被交叉编译器使用，GCC并不安装任何文件到里
面。

@code{TOOL_INCLUDE_DIR} 被本地和交叉编译器共同使用。这是其它安装包安
装头文件以供GCC使用的地方。对于交叉编译器，这相当于 
@file{/usr/include}。当构建交叉编译器时，@code{fixincludes} 会处理该
目录下的任何文件。
