@ignore
@c Set file name and title for man page.
@setfilename gpl
@en @settitle GNU General Public License
@settitle GNU 通用公共许可
@c man begin SEEALSO
gfdl(7), fsf-funding(7).
@c man end
@c man begin COPYRIGHT
Copyright @copyright{} 2007 Free Software Foundation, Inc.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.
@c man end
@end ignore
@node Copying
@c man begin DESCRIPTION
@en @unnumbered GNU General Public License
@unnumbered GNU 通用公共许可
@center Version 3, 29 June 2007

@c This file is intended to be included in another file.

@display
@en Copyright @copyright{} 2007 Free Software Foundation, Inc. @url{http://fsf.org/}
版权所有 @copyright{} 2007 Free Software Foundation, Inc. @url{http://fsf.org/}

@en Everyone is permitted to copy and distribute verbatim copies of this
@en license document, but changing it is not allowed.
允许所有人复制和发布本授权文件的完整版本，但不允许对它进行任何修改。
@end display

@en @heading Preamble
@heading 导言

@en The GNU General Public License is a free, copyleft license for
@en software and other kinds of works.
GNU 通用公共授权是一份针对软件和其他种类作品的自由的、公共的授权文件。 

@en The licenses for most software and other practical works are designed
@en to take away your freedom to share and change the works.  By contrast,
@en the GNU General Public License is intended to guarantee your freedom
@en to share and change all versions of a program--to make sure it remains
@en free software for all its users.  We, the Free Software Foundation,
@en use the GNU General Public License for most of our software; it
@en applies also to any other work released this way by its authors.  You
@en can apply it to your programs, too.
大多数软件授权申明被设计为剥夺您共享和修改软件的自由。相反地，GNU 通用公共授权力图保护您分享和修改自由软件地自由——以确保软件对所有使用者都是自由的。我们，自由软件基金会，对我们的大多数软件使用 GNU 通用公共授权；本授权同样适用于任何其作者以这种方式发布的软件。您也可以让您的软件使用本授权。 

@en When we speak of free software, we are referring to freedom, not
@en price.  Our General Public Licenses are designed to make sure that you
@en have the freedom to distribute copies of free software (and charge for
@en them if you wish), that you receive source code or can get it if you
@en want it, that you can change the software or use pieces of it in new
@en free programs, and that you know you can do these things.
当我们谈论自由软件时，我们指的是行为的自由，而非价格自由。GNU 通用公共授权被设计为确保您拥有发布自由软件副本(以及为此收费，如果您希望的话)的自由,确保您能收到源代码或者在您需要时能获取源代码，确保您能修改软件或者将它的一部分用于新的自由软件，并且确保您知道您能做这些事情。 

@en To protect your rights, we need to prevent others from denying you
@en these rights or asking you to surrender the rights.  Therefore, you
@en have certain responsibilities if you distribute copies of the
@en software, or if you modify it: responsibilities to respect the freedom
@en of others.
为了保护您的权利，我们需要做出要求，禁止任何人否认您的这些权利或者要求您放弃这些权利。因此，如果您发布此软件的副本或者修改它，您就需要肩负起尊重他人自由的责任。 

@en For example, if you distribute copies of such a program, whether
@en gratis or for a fee, you must pass on to the recipients the same
@en freedoms that you received.  You must make sure that they, too,
@en receive or can get the source code.  And you must show them these
@en terms so they know their rights.
例如，如果您发布自由软件的副本，无论以自由还是以收费的模式，您都必须把您获得的自由同样的给予副本的接收者。您必须确保他们也能收到或者得到源代码。而且您必须向他们展示这些条款，以使他们知道自己享有这样的权利。 

@en Developers that use the GNU GPL protect your rights with two steps:
@en (1) assert copyright on the software, and (2) offer you this License
@en giving you legal permission to copy, distribute and/or modify it. 使用 GNU 通用公共授权的开发者通过两项措施来保护您的权利：（1）声明软件的版权；（2）向您提供本授权文件以给您复制、发布并且/或者修改软件的法律许可。

@en For the developers' and authors' protection, the GPL clearly explains
@en that there is no warranty for this free software.  For both users' and
@en authors' sake, the GPL requires that modified versions be marked as
@en changed, so that their problems will not be attributed erroneously to
@en authors of previous versions.
为了保护软件开发者和作者，通用公共授权明确阐释自由软件没有任何担保责任。如用户和软件作者所希望的，通用公共授权要求软件被修改过的版本必须明确标示，从而避免它们的问题被错误地归咎于先前的版本。 

@en Some devices are designed to deny users access to install or run
@en modified versions of the software inside them, although the
@en manufacturer can do so.  This is fundamentally incompatible with the
@en aim of protecting users' freedom to change the software.  The
@en systematic pattern of such abuse occurs in the area of products for
@en individuals to use, which is precisely where it is most unacceptable.
@en Therefore, we have designed this version of the GPL to prohibit the
@en practice for those products.  If such problems arise substantially in
@en other domains, we stand ready to extend this provision to those
@en domains in future versions of the GPL, as needed to protect the
@en freedom of users.
某些设备被设计成拒绝用户安装或运行其内部软件的修改版本，尽管制造商可以安装和运行它们。这从根本上违背了通用公共授权保护用户能修改软件的自由的宗旨。此类滥用本授权的系统模式出现在了最让人无法接受的个人用户产品领域。因此，我们设计了这个版本的通用公共授权来禁止那些产品的侵权行为。如果此类问题在其他领域大量出现，我们准备好了在将来的通用公共授权版本里扩展这项规定，以保护用户的自由。 

@en Finally, every program is threatened constantly by software patents.
@en States should not allow patents to restrict development and use of
@en software on general-purpose computers, but in those that do, we wish
@en to avoid the special danger that patents applied to a free program
@en could make it effectively proprietary.  To prevent this, the GPL
@en assures that patents cannot be used to render the program non-free.
最后，每个程序都经常受到软件专利的威胁。政府不应该允许专利权限制通用计算机软件的发展和使用，但是在政府确实允许这种事情的地区，我们希望避免应用于自由软件的专利权使该软件有效私有化的危险。为了阻止这样的事情的发生，通用公共授权确保没有人能够使用专利权使得自由软件非自由化。 

@en The precise terms and conditions for copying, distribution and
@en modification follow.
以下是复制、分发和修改软件的详细条款和条件。 

@en @heading TERMS AND CONDITIONS
@heading 条款和条件

@enumerate 0
@en @item Definitions.
@item 定义  

@en ``This License'' refers to version 3 of the GNU General Public License.
``本授权''指 GNU 通用公共授权第三版 

@en ``Copyright'' also means copyright-like laws that apply to other kinds
@en of works, such as semiconductor masks.
``版权''一词同样指适用于其他产品如半导体掩膜等的保护版权的法律。 

@en ``The Program'' refers to any copyrightable work licensed under this
@en License.  Each licensee is addressed as ``you''.  ``Licensees'' and
@en ``recipients'' may be individuals or organizations.
``本程序''指任何在本授权下发布的受版权保护的作品。被授权人称为``您''。``被授权人''和``版权接受者''可以是个人或组织。 

@en To ``modify'' a work means to copy from or adapt all or part of the work
@en in a fashion requiring copyright permission, other than the making of
@en an exact copy.  The resulting work is called a ``modified version'' of
@en the earlier work or a work ``based on'' the earlier work.
``修改''作品是指从软件中拷贝或者做出全部或一丁点儿的修改，这不同于逐字逐句的复制，是需要版权许可的。修改成果被称为先前作品的``修改版本''或者``基于''先前作品的软件。 

@en A ``covered work'' means either the unmodified Program or a work based
@en on the Program.
``覆盖程序''指未被修改过的本程序或者基于本程序的程序。 

@en To ``propagate'' a work means to do anything with it that, without
@en permission, would make you directly or secondarily liable for
@en infringement under applicable copyright law, except executing it on a
@en computer or modifying a private copy.  Propagation includes copying,
@en distribution (with or without modification), making available to the
@en public, and in some countries other activities as well.
``传播''程序指使用该程序做任何如果没有许可就会在适用的版权法下直接或间接侵权的事情，不包括在电脑上执行程序或者是做出您不与人共享的修改。传播包括复制，分发（无论修改与否），向公众共享，以及在某些国家的其他行为。

@en To ``convey'' a work means any kind of propagation that enables other
@en parties to make or receive copies.  Mere interaction with a user
@en through a computer network, with no transfer of a copy, is not
@en conveying.
``发布''作品指任何让其他组织制作或者接受副本的传播行为。仅仅通过电脑网络和一个用户交流，且没有发送程序拷贝的行为不是发布。 

@en An interactive user interface displays ``Appropriate Legal Notices'' to
@en the extent that it includes a convenient and prominently visible
@en feature that (1) displays an appropriate copyright notice, and (2)
@en tells the user that there is no warranty for the work (except to the
@en extent that warranties are provided), that licensees may convey the
@en work under this License, and how to view a copy of this License.  If
@en the interface presents a list of user commands or options, such as a
@en menu, a prominent item in the list meets this criterion.
一个显示``适当的法律通告''的交互的用户接口应包括这样一个方便而显著的可视部件，它具有以下功能：（1）显示一个合适的版权通告；（2）告诉用户对本程序没有任何担保责任（除非有担保明确告知），受权人可以在本授权下发布本程序，以及如果阅读本授权协议的副本。如果该接口显示了一个用户命令或选项列表，比如菜单，该列表中的选项需要符合上述规范。

@en @item Source Code.
@item 源代码

@en The ``source code'' for a work means the preferred form of the work for
@en making modifications to it.  ``Object code'' means any non-source form
@en of a work.
``源代码''指修改程序常用的形式。``目标代码''指程序的任何非源代码形式。 

@en A ``Standard Interface'' means an interface that either is an official
@en standard defined by a recognized standards body, or, in the case of
@en interfaces specified for a particular programming language, one that
@en is widely used among developers working in that language.
``标准接口''有两种含义,一是由标准组织分支定义的官方标准；二是针对某种语言专门定义的众多接口中，在该类语言的开发者中广为使用的那种接口。 

@en The ``System Libraries'' of an executable work include anything, other
@en than the work as a whole, that (a) is included in the normal form of
@en packaging a Major Component, but which is not part of that Major
@en Component, and (b) serves only to enable use of the work with that
@en Major Component, or to implement a Standard Interface for which an
@en implementation is available to the public in source code form.  A
@en ``Major Component'', in this context, means a major essential component
@en (kernel, window system, and so on) of the specific operating system
@en (if any) on which the executable work runs, or a compiler used to
@en produce the work, or an object code interpreter used to run it.
可执行程序的``系统库''不是指整个程序，而是指任何包含于主要部件但不属于该部件的部分，并且只是为了使能该部件而开发，或者为了实现某些已有公开源代码的标准接口。``主要部件''在这里指的是执行程序的特定操作系统（如果有的话）的主要的关键部件（内核，窗口系统等），或者生成该可执行程序时使用的编译器，或者运行该程序的目标代码解释器。 

@en The ``Corresponding Source'' for a work in object code form means all
@en the source code needed to generate, install, and (for an executable
@en work) run the object code and to modify the work, including scripts to
@en control those activities.  However, it does not include the work's
@en System Libraries, or general-purpose tools or generally available free
@en programs which are used unmodified in performing those activities but
@en which are not part of the work.  For example, Corresponding Source
@en includes interface definition files associated with source files for
@en the work, and the source code for shared libraries and dynamically
@en linked subprograms that the work is specifically designed to require,
@en such as by intimate data communication or control flow between those
@en subprograms and other parts of the work.
目标代码中的程序``对应的源代码''指所有生成，安装，（对可执行程序而言）运行该目标代码和修改该程序所需要的源代码，包括控制这些行为的脚本。但是，它不包括程序需要的系统库，通用目的的工具，以及程序在完成某些功能时不经修改地使用的那些不包括在程序中的普遍可用的自由软件。例如，对应的源代码包括与程序的源文件相关的接口定义文件，以及共享库中的源代码和该程序设计需要的通过如频繁的数据交互或者这些子程序和该程序其他部分之间的控制流等方式获得的动态链接子程序。

@en The Corresponding Source need not include anything that users can
@en regenerate automatically from other parts of the Corresponding Source.
对应的源代码不需要包含任何拥护可以从这些资源的其他部分自动再生的资源。

@en The Corresponding Source for a work in source code form is that same
@en work.
源代码形式的程序对应的源代码定义同上。

@en @item Basic Permissions.
@item 基本的许可

@en All rights granted under this License are granted for the term of
@en copyright on the Program, and are irrevocable provided the stated
@en conditions are met.  This License explicitly affirms your unlimited
@en permission to run the unmodified Program.  The output from running a
@en covered work is covered by this License only if the output, given its
@en content, constitutes a covered work.  This License acknowledges your
@en rights of fair use or other equivalent, as provided by copyright law.
所有在本授权协议下授予的权利都是对本程序的版权而言，并且只要所述的条件都满足了，这些授权是不能收回的。本授权明确的确认您可以不受任何限制地运行本程序的未修改版本。运行一个本授权覆盖的程序获得的结果只有在该结果的内容构成一个覆盖程序的时候才由本授权覆盖。本授权承认您正当使用或版权法规定的其它类似行为的权利。 

@en You may make, run and propagate covered works that you do not convey,
@en without conditions so long as your license otherwise remains in force.
@en You may convey covered works to others for the sole purpose of having
@en them make modifications exclusively for you, or provide you with
@en facilities for running those works, provided that you comply with the
@en terms of this License in conveying all material for which you do not
@en control copyright.  Those thus making or running the covered works for
@en you must do so exclusively on your behalf, under your direction and
@en control, on terms that prohibit them from making any copies of your
@en copyrighted material outside their relationship with you.
只要您的授权仍然有效，您可以无条件地制作，运行和传播那些您不发布的覆盖程序。只要您遵守本授权中关于发布您不具有版权的资料的条款，您可以向别人发布覆盖程序，以要求他们为您做出专门的修改或者向您提供运行这些程序的简易设备。那些为您制作或运行覆盖程序的人作为您专门的代表也必须在您的指示和控制下做到这些，请禁止他们在他们和您的关系之外制作任何您拥有版权的程序的副本。 

@en Conveying under any other circumstances is permitted solely under the
@en conditions stated below.  Sublicensing is not allowed; section 10
@en makes it unnecessary.
当下述条件满足的时候，在任何其他情况下的发布都是允许的。转授许可证授权是不允许的，第10节让它变的没有必要了。 

@en @item Protecting Users' Legal Rights From Anti-Circumvention Law.
@item 保护用户的合法权利不受反破解法侵犯 

@en No covered work shall be deemed part of an effective technological
@en measure under any applicable law fulfilling obligations under article
@en 11 of the WIPO copyright treaty adopted on 20 December 1996, or
@en similar laws prohibiting or restricting circumvention of such
@en measures.
在任何实现1996年通过的世界知识产权组织版权条约第11章中所述任务的法律，或者是禁止或限制这种破解方法的类似法律下，覆盖程序都不会被认定为有效的技术手段的一部分。 

@en When you convey a covered work, you waive any legal power to forbid
@en circumvention of technological measures to the extent such
@en circumvention is effected by exercising rights under this License with
@en respect to the covered work, and you disclaim any intention to limit
@en operation or modification of the work as a means of enforcing, against
@en the work's users, your or third parties' legal rights to forbid
@en circumvention of technological measures.
当您发布一个覆盖程序时，您将放弃任何禁止技术手段破解的法律力量，甚至在本授权关于覆盖程序的条款下执行权利也能完成破解。同时，您放弃任何限制用户操作或修改该覆盖程序以执行您禁止技术手段破解的合法权利的企图。

@en @item Conveying Verbatim Copies.
@item 发布完整副本

@en You may convey verbatim copies of the Program's source code as you
@en receive it, in any medium, provided that you conspicuously and
@en appropriately publish on each copy an appropriate copyright notice;
@en keep intact all notices stating that this License and any
@en non-permissive terms added in accord with section 7 apply to the code;
@en keep intact all notices of the absence of any warranty; and give all
@en recipients a copy of this License along with the Program.
你可以通过任何媒介发布本程序源代码的未被修改过的完整副本，只要您显著而适当地在每个副本上发布一个合适的版权通告；保持完整所有叙述本授权和任何按照第7节加入的非许可的条款；保持完整所有的免责申明；并随程序给所有的接受者一份本授权。 

@en You may charge any price or no price for each copy that you convey,
@en and you may offer support or warranty protection for a fee.
您可以为您的副本收取任何价格的费用或者自由，你也可以提供技术支持或者责任担保来收取费用。 

@en @item Conveying Modified Source Versions.
@item 发布修改过的源码版本

@en You may convey a work based on the Program, or the modifications to
@en produce it from the Program, in the form of source code under the
@en terms of section 4, provided that you also meet all of these
@en conditions:
您可以在第 4 节的条款下以源码形式发布一个基于本程序的软件，或者从本程序中制作该软件需要进行的修改，只要您同时满足所有以下条件： 

@enumerate a
@item 
@en The work must carry prominent notices stating that you modified it,
@en and giving a relevant date.
制作的软件必须包含明确的通告说明您修改了它，并给出相应的修改日期。 

@item
@en The work must carry prominent notices stating that it is released
@en under this License and any conditions added under section 7.  This
@en requirement modifies the requirement in section 4 to ``keep intact all
@en notices''.
制作的软件必须包含明确的通告，陈述它在本授权下发布并指出任何按照第7节加入的条件。这条要求修改了第4节的``保持所有通知完整''的要求。 

@item
@en You must license the entire work, as a whole, under this License to
@en anyone who comes into possession of a copy.  This License will
@en therefore apply, along with any applicable section 7 additional terms,
@en to the whole of the work, and all its parts, regardless of how they
@en are packaged.  This License gives no permission to license the work in
@en any other way, but it does not invalidate such permission if you have
@en separately received it.
您必须把整个软件作为一个整体向任何获取副本的人按照本授权协议授权。本授权因此会和任何按照第7节加入的条款一起，对整个软件及其所有部分，无论是以什么形式打包的，起法律效力。本授权不允许以其他任何形式授权该软件，但如果您个别地收到这样的许可，本授权并不否定该许可。 

@item
@en If the work has interactive user interfaces, each must display
@en Appropriate Legal Notices; however, if the Program has interactive
@en interfaces that do not display Appropriate Legal Notices, your work
@en need not make them do so.
如果您制作的软件包含交互的用户接口，每个用户接口都必须显示适当的法律通告；但是，如果本程序包含没有显示适当的法律通告的交互接口，您的软件没有必要修改他们让他们显示。 
@end enumerate

@en A compilation of a covered work with other separate and independent
@en works, which are not by their nature extensions of the covered work,
@en and which are not combined with it such as to form a larger program,
@en in or on a volume of a storage or distribution medium, is called an
@en ``aggregate'' if the compilation and its resulting copyright are not
@en used to limit the access or legal rights of the compilation's users
@en beyond what the individual works permit.  Inclusion of a covered work
@en in an aggregate does not cause this License to apply to the other
@en parts of the aggregate.
如果一个覆盖程序和其他本身不是该程序的扩展的程序的联合体，这样的联合的目的不是为了在某个存储或发布媒体上生成更大的程序，且联合体程序和相应产生的版权没有用来限制程序的使用或限制单个程序赋予的联合程序的用户的合法权利的时候，这样的联合体就被称为``聚集体''。在聚集体中包含覆盖程序并不会使本授权应用于该聚集体的其他部分。 

@en @item  Conveying Non-Source Forms.
@item  发布非源码形式的副本

@en You may convey a covered work in object code form under the terms of
@en sections 4 and 5, provided that you also convey the machine-readable
@en Corresponding Source under the terms of this License, in one of these
@en ways:
您可以在第 4, 5 节条款下以目标代码形式发布程序，只要您同时以一下的一种方式在本授权条款下发布机器可读的对应的源代码： 

@enumerate a
@item
@en Convey the object code in, or embodied in, a physical product
@en (including a physical distribution medium), accompanied by the
@en Corresponding Source fixed on a durable physical medium customarily
@en used for software interchange.
在物理产品（包括一个物理的发布媒介）中或作为其一部分发布目标代码，并在通常用于软件交换的耐用的物理媒介中发布对应的源代码。

@item
@en Convey the object code in, or embodied in, a physical product
@en (including a physical distribution medium), accompanied by a written
@en offer, valid for at least three years and valid for as long as you
@en offer spare parts or customer support for that product model, to give
@en anyone who possesses the object code either (1) a copy of the
@en Corresponding Source for all the software in the product that is
@en covered by this License, on a durable physical medium customarily used
@en for software interchange, for a price no more than your reasonable
@en cost of physically performing this conveying of source, or (2) access
@en to copy the Corresponding Source from a network server at no charge.
在物理产品（包括一个物理的发布媒介）中或作为其一部分发布目标代码，并附上有效期至少3年且与您为该产品模型提供配件或客户服务的时间等长的书面承诺，给予每个拥有该目标代码的人（1）要么在通常用于软件交换的耐用物理媒介中，以不高于您执行这种源码的发布行为所花费的合理费用的价格，一份该产品中所有由本授权覆盖的软件的对应的源代码的拷贝；（2）要么通过网络服务器自由提供这些对应源代码的访问。 

@item
@en Convey individual copies of the object code with a copy of the written
@en offer to provide the Corresponding Source.  This alternative is
@en allowed only occasionally and noncommercially, and only if you
@en received the object code with such an offer, in accord with subsection
@en 6b.
单独地发布目标代码的副本，并附上一份提供对应源代码的书面承诺。这种行为只允许偶尔发生并不能盈利，且在您收到的目标代码附有第6节b规定的承诺的时候。 

@item
@en Convey the object code by offering access from a designated place
@en (gratis or for a charge), and offer equivalent access to the
@en Corresponding Source in the same way through the same place at no
@en further charge.  You need not require recipients to copy the
@en Corresponding Source along with the object code.  If the place to copy
@en the object code is a network server, the Corresponding Source may be
@en on a different server (operated by you or a third party) that supports
@en equivalent copying facilities, provided you maintain clear directions
@en next to the object code saying where to find the Corresponding Source.
@en Regardless of what server hosts the Corresponding Source, you remain
@en obligated to ensure that it is available for as long as needed to
@en satisfy these requirements.
在指定的地点（自由或收费地）提供发布的目标代码的访问并在同样的地点以不增加价格的方式提供对应源代码的同样的访问权。您不需要要求接收者在复制目标代码的时候一道复制对应的源代码。如果复制目标代码的地点是网络服务器，对应的源代码可以在另外一个支持相同复制功能的服务器上（由您或者第三方运作），只要您在目标代码旁边明确指出在哪里可以找到对应的源代码。无论什么样的服务器提供这些对应的源代码，您都有义务保证它在任何有需求的时候都可用，从而满足本条规定。 

@item
@en Convey the object code using peer-to-peer transmission, provided you
@en inform other peers where the object code and Corresponding Source of
@en the work are being offered to the general public at no charge under
@en subsection 6d.
用点对点传输发布目标代码，您需要告知其他的节点目标代码和对应的源代码在哪里按照第6节d的条款向大众自由提供。 

@end enumerate

@en A separable portion of the object code, whose source code is excluded
@en from the Corresponding Source as a System Library, need not be
@en included in conveying the object code work.
目标代码中可分离的部分，其源代码作为系统库不包含在对应的源代码中，不需要包含在发布目标代码的行为中。 

@en A ``User Product'' is either (1) a ``consumer product'', which means any
@en tangible personal property which is normally used for personal,
@en family, or household purposes, or (2) anything designed or sold for
@en incorporation into a dwelling.  In determining whether a product is a
@en consumer product, doubtful cases shall be resolved in favor of
@en coverage.  For a particular product received by a particular user,
@en ``normally used'' refers to a typical or common use of that class of
@en product, regardless of the status of the particular user or of the way
@en in which the particular user actually uses, or expects or is expected
@en to use, the product.  A product is a consumer product regardless of
@en whether the product has substantial commercial, industrial or
@en non-consumer uses, unless such uses represent the only significant
@en mode of use of the product.
``用户产品''指（1）``消费品''，即通常用于个人的、家庭的或日常目的的有形个人财产；或者（2）任何为公司设计或销售却卖给了个人的东西。在判断一个产品是否消费品时，有疑点的案例将以有利于覆盖面的结果加以判断。对特定用户接收到的特定产品，``正常使用''指该类产品的典型的或通常的使用，无论该用户的特殊情况，或者该用户实际使用该产品的情况，或者该产品要求的使用方式如何。一个产品是否是消费品与该产品是否具有实质的经济上的、工业的或非消费品的用处无关，除非该用处是此类产品唯一的重要使用模式。 

@en ``Installation Information'' for a User Product means any methods,
@en procedures, authorization keys, or other information required to
@en install and execute modified versions of a covered work in that User
@en Product from a modified version of its Corresponding Source.  The
@en information must suffice to ensure that the continued functioning of
@en the modified object code is in no case prevented or interfered with
@en solely because modification has been made.
用户产品的``安装信息''指从对应源码的修改版本安装和运行该用户产品中包含的覆盖程序的修改版本所需要的任何方法、过程、授权密钥或其他信息。这些信息必须足以保证修改后的目标代码不会仅仅因为被修改过而不能继续运行。 

@en If you convey an object code work under this section in, or with, or
@en specifically for use in, a User Product, and the conveying occurs as
@en part of a transaction in which the right of possession and use of the
@en User Product is transferred to the recipient in perpetuity or for a
@en fixed term (regardless of how the transaction is characterized), the
@en Corresponding Source conveyed under this section must be accompanied
@en by the Installation Information.  But this requirement does not apply
@en if neither you nor any third party retains the ability to install
@en modified object code on the User Product (for example, the work has
@en been installed in ROM).
如果您在本节条款下在用户产品中，或随同，或专门为了其中的使用，发布目标代码程序，而在发布过程中用户产品的所有权和使用权都永久地或在一定时期内（无论此项发布的特点如何）传递给了接收者，在本节所述的条款下发布的对应的源代码必须包含安装信息。但是如果您或者任何第三方组织都没有保留在用户产品上安装修改过的目标代码的能力（比如程序被安装在了ROM上），那么这项要求不会生效。 

@en The requirement to provide Installation Information does not include a
@en requirement to continue to provide support service, warranty, or
@en updates for a work that has been modified or installed by the
@en recipient, or for the User Product in which it has been modified or
@en installed.  Access to a network may be denied when the modification
@en itself materially and adversely affects the operation of the network
@en or violates the rules and protocols for communication across the
@en network.
提供安装信息的要求并没有要求为接收者修改或安装过的程序，或者修改或安装该程序的用户产品，继续提供支持服务、担保或升级。当修改本身实际上相反地影响了网络的运行，或者违反了网络通信的规则和协议时，网络访问可以被拒绝。 

@en Corresponding Source conveyed, and Installation Information provided,
@en in accord with this section must be in a format that is publicly
@en documented (and with an implementation available to the public in
@en source code form), and must require no special password or key for
@en unpacking, reading or copying.
根据本节发布的对应源代码和提供的安装信息必须以公共的文件格式发布（并附加一个该类型文档的实现方法以源码形式向公众共享），解压缩、阅读或复制这些信息不能要求任何密码。 

@en @item Additional Terms.
@item 附加条款

@en ``Additional permissions'' are terms that supplement the terms of this
@en License by making exceptions from one or more of its conditions.
@en Additional permissions that are applicable to the entire Program shall
@en be treated as though they were included in this License, to the extent
@en that they are valid under applicable law.  If additional permissions
@en apply only to part of the Program, that part may be used separately
@en under those permissions, but the entire Program remains governed by
@en this License without regard to the additional permissions.
``附加许可''是通过允许一些本授权的特例来补充本授权的条款。只要它们在使用法律下合法，对整个程序都生效的附加许可就应当被认为是本授权的内容。如果附加许可只是对本程序的一部分生效，那么该部分可以在那些许可下独立使用，但整个程序是在本授权管理下，无论附加许可如何。 

@en When you convey a copy of a covered work, you may at your option
@en remove any additional permissions from that copy, or from any part of
@en it.  (Additional permissions may be written to require their own
@en removal in certain cases when you modify the work.)  You may place
@en additional permissions on material, added by you to a covered work,
@en for which you have or can give appropriate copyright permission.
当您发布覆盖程序的副本时，您可以选择删除该副本或其部分的任何附加许可。（当您修改程序时，附加许可可能要求在某些情况下将自身删除）。您可以把附加许可放在材料上，加入到您拥有或能授予版权许可的覆盖程序中。 

@en Notwithstanding any other provision of this License, for material you
@en add to a covered work, you may (if authorized by the copyright holders
@en of that material) supplement the terms of this License with terms:
尽管本授权在别处有提供，对于您加入到程序中的材料，您可以（如果您由该材料的版权所有者授权的话）用以下条款补充本授权： 

@enumerate a
@item
@en Disclaiming warranty or limiting liability differently from the terms
@en of sections 15 and 16 of this License; or
拒绝担保责任或以与本授权第15和16小节条款不同的方式限制责任；或者 

@item
@en Requiring preservation of specified reasonable legal notices or author
@en attributions in that material or in the Appropriate Legal Notices
@en displayed by works containing it; or
要求保留特定的合理法律通告，或者该材料中或包含于适当法律通告中的该程序的作者贡献；或者 

@item
@en Prohibiting misrepresentation of the origin of that material, or
@en requiring that modified versions of such material be marked in
@en reasonable ways as different from the original version; or
禁止误传该材料的来源，或者要求该材料的修改版本以合理的方式标志为与原版本不同的版本；或者 

@item
@en Limiting the use for publicity purposes of names of licensors or
@en authors of the material; or
限制以宣传为目的的使用该材料作者或授权人的姓名；或者 

@item
@en Declining to grant rights under trademark law for use of some trade
@en names, trademarks, or service marks; or
降低授权级别以在商标法下使用一些商品名称，商标或服务标记；或者 

@item
@en Requiring indemnification of licensors and authors of that material by
@en anyone who conveys the material (or modified versions of it) with
@en contractual assumptions of liability to the recipient, for any
@en liability that these contractual assumptions directly impose on those
@en licensors and authors.
要求任何发布该材料（或其修改版本）的人用对接收者的责任假设合同对授权人和材料作者进行保护，避免任何这样的假设合同直接造成授权人和作者的责任。 
@end enumerate

@en All other non-permissive additional terms are considered ``further
@en restrictions'' within the meaning of section 10.  If the Program as you
@en received it, or any part of it, contains a notice stating that it is
@en governed by this License along with a term that is a further
@en restriction, you may remove that term.  If a license document contains
@en a further restriction but permits relicensing or conveying under this
@en License, you may add to a covered work material governed by the terms
@en of that license document, provided that the further restriction does
@en not survive such relicensing or conveying.
所有其他不许可的附加条款都被认为是第10节中的``进一步的约束''。如果您收到的程序或者其部分，声称自己由本授权管理，并补充了进一步约束，那么您可以删除这些约束。如果一个授权文件包含进一步约束，但是允许再次授权或者在本授权下发布，只要这样的进一步的约束在这样的再次授权或发布中无法保留下来，您就可以在覆盖程序中加入该授权文件条款管理下的材料。 

@en If you add terms to a covered work in accord with this section, you
@en must place, in the relevant source files, a statement of the
@en additional terms that apply to those files, or a notice indicating
@en where to find the applicable terms.
如果您依据本小节向覆盖程序添加条款,您必须在相关的源码文件中加入一个应用于那些文件的附加条款的声明或者指明在哪里可以找到这些条款的通告。 

@en Additional terms, permissive or non-permissive, may be stated in the
@en form of a separately written license, or stated as exceptions; the
@en above requirements apply either way.
附加的条款，无论是许可的还是非许可的条款，都可以写在一个单独的书面授权中，或者申明为例外情况；这两种方法都可以实现上述要求。 

@en @item Termination.
@item 终止授权

@en You may not propagate or modify a covered work except as expressly
@en provided under this License.  Any attempt otherwise to propagate or
@en modify it is void, and will automatically terminate your rights under
@en this License (including any patent licenses granted under the third
@en paragraph of section 11).
您只有在本授权的明确授权下才能传播或修改覆盖程序。任何其它的传播或修改覆盖程序的尝试都是非法的，并将自动终止您在本授权下获取的权利（包括依据第11节第三段条款授予的任何专利授权）。 

@en However, if you cease all violation of this License, then your license
@en from a particular copyright holder is reinstated (a) provisionally,
@en unless and until the copyright holder explicitly and finally
@en terminates your license, and (b) permanently, if the copyright holder
@en fails to notify you of the violation by some reasonable means prior to
@en 60 days after the cessation.
然而，如果您停止违反本授权，那么您从某个特定版权所有者处获取的授权许可能够以以下方式恢复（a）您可以暂时地拥有授权，直到版权所有者明确地终止您的授权；（b）如果在您停止违反本授权后的60天内，版权所有者没有以某种合理的方式告知您的违背行为，那么您可以永久地获取该授权。 

@en Moreover, your license from a particular copyright holder is
@en reinstated permanently if the copyright holder notifies you of the
@en violation by some reasonable means, this is the first time you have
@en received notice of violation of this License (for any work) from that
@en copyright holder, and you cure the violation prior to 30 days after
@en your receipt of the notice.
进一步地，如果某个版权所有者以某种合理的方式告知您违反本授权的行为，而这是您第一次收到来自该版权所有者的违反本授权的通知（对任何软件），并且在收到通知后30天内修正了违反行为，那么您从该版权所有者处获取的授权将永久地恢复。 

@en Termination of your rights under this section does not terminate the
@en licenses of parties who have received copies or rights from you under
@en this License.  If your rights have been terminated and not permanently
@en reinstated, you do not qualify to receive new licenses for the same
@en material under section 10.
当您的授权在本节条款下被终止时，那些从您那获取授权的组织只要保持不违反本授权协议，其授权就不会被终止。您只有在授权被版权所有者恢复了之后才有资格依据第10节的条款获取该材料的新的授权。 

@en @item Acceptance Not Required for Having Copies.
@item 获取副本不需要接受本授权 

@en You are not required to accept this License in order to receive or run
@en a copy of the Program.  Ancillary propagation of a covered work
@en occurring solely as a consequence of using peer-to-peer transmission
@en to receive a copy likewise does not require acceptance.  However,
@en nothing other than this License grants you permission to propagate or
@en modify any covered work.  These actions infringe copyright if you do
@en not accept this License.  Therefore, by modifying or propagating a
@en covered work, you indicate your acceptance of this License to do so.
您不需要为了接收或运行本程序的副本而接受本授权协议。仅仅是因为点对点传输获取副本引起传播行为，也不要求您接受本授权协议。然而，除了本授权外，任何授权协议都不能授予您传播或修改覆盖程序的许可。因此，如果您修改或者传播了本程序的副本，那么您就默认地接受了本授权。 

@en @item Automatic Licensing of Downstream Recipients.
@item 下游接收者的自动授权 

@en Each time you convey a covered work, the recipient automatically
@en receives a license from the original licensors, to run, modify and
@en propagate that work, subject to this License.  You are not responsible
@en for enforcing compliance by third parties with this License.
每次您发布更新的程序，接收者都自动获得一份来自原授权人的依照本授权协议运行、修改和传播该程序的授权。依据本授权，您不为执行任何第三方组织的要求负责。 

@en An ``entity transaction'' is a transaction transferring control of an
@en organization, or substantially all assets of one, or subdividing an
@en organization, or merging organizations.  If propagation of a covered
@en work results from an entity transaction, each party to that
@en transaction who receives a copy of the work also receives whatever
@en licenses to the work the party's predecessor in interest had or could
@en give under the previous paragraph, plus a right to possession of the
@en Corresponding Source of the work from the predecessor in interest, if
@en the predecessor has it or can get it with reasonable efforts.
``实体事务''指转移一个组织的控制权或全部资产，或者拆分组织，或者合并组织的事务。如果覆盖程序的传播是实体事务造成的，该事务中每一个接收本程序副本的组织都将获取一份其前身拥有的或者能够依据前面的条款提供的任何授权，以及从其前身获取程序对应的源代码的权利，如果前身拥有或以合理的努力能够获取这些源代码的话。 

@en You may not impose any further restrictions on the exercise of the
@en rights granted or affirmed under this License.  For example, you may
@en not impose a license fee, royalty, or other charge for exercise of
@en rights granted under this License, and you may not initiate litigation
@en (including a cross-claim or counterclaim in a lawsuit) alleging that
@en any patent claim is infringed by making, using, selling, offering for
@en sale, or importing the Program or any portion of it.
您不可以对从本授权协议获取或确认的权利的执行强加任何约束。比如，您不可以要求授权费用，版税要求或对从本授权获取的权利的执行收取任何费用。您不可以发起诉讼（包括联合诉讼和反诉）声称由于制作、使用、销售、批发或者引进本程序或其任何一部分而侵犯了任何专利权。 

@en @item Patents.
@item 专利权

@en A ``contributor'' is a copyright holder who authorizes use under this
@en License of the Program or a work on which the Program is based.  The
@en work thus licensed is called the contributor's ``contributor version''.
``贡献者''是在本授权下授予本程序或者本程序所基于的程序的使用权的版权所有者。这样的程序被成为贡献者的``贡献者版本''。 

@en A contributor's ``essential patent claims'' are all patent claims owned
@en or controlled by the contributor, whether already acquired or
@en hereafter acquired, that would be infringed by some manner, permitted
@en by this License, of making, using, or selling its contributor version,
@en but do not include claims that would be infringed only as a
@en consequence of further modification of the contributor version.  For
@en purposes of this definition, ``control'' includes the right to grant
@en patent sublicenses in a manner consistent with the requirements of
@en this License.
一个贡献者的``实质的专利申明''是该贡献者所占有和控制的全部专利，无论已经获得的还是在将来获得的，那些可能受到某种方式侵犯的专利权。本授权允许制作、使用和销售其贡献者版本，但不包括那些只会由于对贡献者版本进一步的修改而受到侵犯的专利的申明。为此，``控制''一词包括以同本授权要求一致的方式给予从属授权的权利。 

@en Each contributor grants you a non-exclusive, worldwide, royalty-free
@en patent license under the contributor's essential patent claims, to
@en make, use, sell, offer for sale, import and otherwise run, modify and
@en propagate the contents of its contributor version.
每个贡献者在该贡献者的实质的专利申明下授予您非独家的，全世界的，不需要版税的专利授权，允许您制作、使用、销售、批发、进口以及运行、修改和传播其贡献者版本内容。 

@en In the following three paragraphs, a ``patent license'' is any express
@en agreement or commitment, however denominated, not to enforce a patent
@en (such as an express permission to practice a patent or covenant not to
@en sue for patent infringement).  To ``grant'' such a patent license to a
@en party means to make such an agreement or commitment not to enforce a
@en patent against the party.
在以下三个自然段中，``专利授权''指任何形式表达的不执行专利权的协议或承诺（例如使用专利权的口头许可，或者不为侵犯专利而起诉的契约）。向一个组织授予专利授权指做出这样的不向该组织提出强制执行专利权的承诺。 

@en If you convey a covered work, knowingly relying on a patent license,
@en and the Corresponding Source of the work is not available for anyone
@en to copy, free of charge and under the terms of this License, through a
@en publicly available network server or other readily accessible means,
@en then you must either (1) cause the Corresponding Source to be so
@en available, or (2) arrange to deprive yourself of the benefit of the
@en patent license for this particular work, or (3) arrange, in a manner
@en consistent with the requirements of this License, to extend the patent
@en license to downstream recipients.  ``Knowingly relying'' means you have
@en actual knowledge that, but for the patent license, your conveying the
@en covered work in a country, or your recipient's use of the covered work
@en in a country, would infringe one or more identifiable patents in that
@en country that you have reason to believe are valid.
如果您在自己明确知道的情况下发布基于某个专利授权的覆盖程序，而这个程序的对应的源代码并不能在本授权条款下通过网络服务器或其他有效途径自由地向公众提供访问，您必须做到：（1）使对应的源代码按照上述方法可访问；或者（2）放弃从该程序的专利授权获取任何利益；或者（3）以某种与本授权要求一致的方法使该专利授权延伸到下游的接收者。``在自己明确知道的情况下''指您明确地知道除了获取专利授权外，在某个国家您传播覆盖程序的行为，或者接收者使用覆盖程序的行为，会由于该专利授权而侵犯一个或多个在该国可确认的专利权，而这些专利权您有足够的理由相信它们是有效的。 

@en If, pursuant to or in connection with a single transaction or
@en arrangement, you convey, or propagate by procuring conveyance of, a
@en covered work, and grant a patent license to some of the parties
@en receiving the covered work authorizing them to use, propagate, modify
@en or convey a specific copy of the covered work, then the patent license
@en you grant is automatically extended to all recipients of the covered
@en work and works based on it.
在依照或者涉及某一次事务或安排时，如果您通过获取发布或传播覆盖程序的传输版本，并给予接收该覆盖程序的某些组织专利授权，允许他们使用，传播，修改或者发布该覆盖程序的特殊版本，那么您赋予这些组织的专利授权将自动延伸到所有该覆盖程序及基于该程序的作品的接收者。 

@en A patent license is ``discriminatory'' if it does not include within the
@en scope of its coverage, prohibits the exercise of, or is conditioned on
@en the non-exercise of one or more of the rights that are specifically
@en granted under this License.  You may not convey a covered work if you
@en are a party to an arrangement with a third party that is in the
@en business of distributing software, under which you make payment to the
@en third party based on the extent of your activity of conveying the
@en work, and under which the third party grants, to any of the parties
@en who would receive the covered work from you, a discriminatory patent
@en license (a) in connection with copies of the covered work conveyed by
@en you (or copies made from those copies), or (b) primarily for and in
@en connection with specific products or compilations that contain the
@en covered work, unless you entered into that arrangement, or that patent
@en license was granted, prior to 28 March 2007.
一份专利授权是``有偏见的''，如果它没有在自身所覆盖的范围内包含，禁止行使，或者要求不执行一个或多个本授权下明确认可的权利。以下情况，您不可以发布一个覆盖程序：如果您与软件发布行业的第三方组织有协议，而该协议要求您根据该程序的发布情况向该组织付费，同时该组织在你们的协议中赋予任何从您那里获得覆盖软件的组织一份有偏见的专利授权，要么（a）连同您所发布的副本（或者从这些副本制作的副本）；要么（b）主要为了并连同某个的产品或者包含该覆盖程序的联合体。如果您签署该协议或获得该专利授权的日期早于2007年3月28日，那么您不受本条款约束。 

@en Nothing in this License shall be construed as excluding or limiting
@en any implied license or other defenses to infringement that may
@en otherwise be available to you under applicable patent law.
本授权的任何部分不会被解释为拒绝或者限制任何暗含的授权或其他在适用专利权法下保护您的专利不受侵犯的措施。 

@en @item No Surrender of Others' Freedom.
@item 不要放弃别人的自由

@en If conditions are imposed on you (whether by court order, agreement or
@en otherwise) that contradict the conditions of this License, they do not
@en excuse you from the conditions of this License.  If you cannot convey
@en a covered work so as to satisfy simultaneously your obligations under
@en this License and any other pertinent obligations, then as a
@en consequence you may not convey it at all.  For example, if you agree
@en to terms that obligate you to collect a royalty for further conveying
@en from those to whom you convey the Program, the only way you could
@en satisfy both those terms and this License would be to refrain entirely
@en from conveying the Program.
如果您遇到了与本授权向矛盾的情况（无论是法庭判决，合同或者其他情况），它们不能使您免去本授权的要求。如果您不能同时按照本授权中的义务和其他相关义务来发布覆盖程序，那么您将不能发布它们。比如，如果您接受了要求您向从您这里或许本程序的人收取版税的条款，您唯一能够同时满足本授权和那些条款的方法是完全不要发布本程序。 

@en @item Use with the GNU Affero General Public License.
@item 和 GNU Affero 通用公共授权一起使用 

@en Notwithstanding any other provision of this License, you have
@en permission to link or combine any covered work with a work licensed
@en under version 3 of the GNU Affero General Public License into a single
@en combined work, and to convey the resulting work.  The terms of this
@en License will continue to apply to the part which is the covered work,
@en but the special requirements of the GNU Affero General Public License,
@en section 13, concerning interaction through a network will apply to the
@en combination as such.
尽管本协议有其他防备条款，您有权把任何覆盖程序和基于第三版 GNU Affero 通用公共授权的程序链接起来，并且发布该联合程序。本授权的条款仍然对您的覆盖程序有效，但是 GNU Affero 通用公共授权第13节关于通过网络交互的要求会对整个联合体有效。

@en @item Revised Versions of this License.
@item 本授权的修订版

@en The Free Software Foundation may publish revised and/or new versions
@en of the GNU General Public License from time to time.  Such new
@en versions will be similar in spirit to the present version, but may
@en differ in detail to address new problems or concerns. 
自由软件基金会有时候可能会发布 GNU 通用软件授权的修订版本和/或新版本。这样的新版本将会和现行版本保持精神上的一致性，但是可能会在细节上有所不同，以处理新的问题和情况。

@en Each version is given a distinguishing version number.  If the Program
@en specifies that a certain numbered version of the GNU General Public
@en License ``or any later version'' applies to it, you have the option of
@en following the terms and conditions either of that numbered version or
@en of any later version published by the Free Software Foundation.  If
@en the Program does not specify a version number of the GNU General
@en Public License, you may choose any version ever published by the Free
@en Software Foundation.
每个版本都有一个单独的版本号。如果本程序指出了应用于本程序的一个特定的 GNU 通用公共授权版本号``以及后续版本''，您将拥有选择该版本或任何由自由软件基金会发布的后续版本中的条款和条件的权利。如果本程序没有指定特定的 GNU 通用公共授权版本号，那么您可以选择任何自由软件基金会已发布的版本。 

@en If the Program specifies that a proxy can decide which future versions
@en of the GNU General Public License can be used, that proxy's public
@en statement of acceptance of a version permanently authorizes you to
@en choose that version for the Program.
如果本程序指出某个代理可以决定将来的GNU通用公共授权是否可以应用于本程序，那么该代理的接受任何版本的公开称述都是您选择该版本应用于本程序的永久认可。 

@en Later license versions may give you additional or different
@en permissions.  However, no additional obligations are imposed on any
@en author or copyright holder as a result of your choosing to follow a
@en later version.
后续的授权版本可能会赋予您额外的或者不同的许可。但是，您对后续版本的选择不会对任何作者和版权所有者强加任何义务。 

@en @item Disclaimer of Warranty.
@item 免责声明

@en THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
@en APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
@en HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM ``AS IS'' WITHOUT
@en WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT
@en LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
@en A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND
@en PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE PROGRAM PROVE
@en DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR
@en CORRECTION.
在适用法律许可下，本授权不对本程序承担任何担保责任。除非是书面申明，否则版权所有者和/或提供本程序的第三方组织，``照旧''不承担任何形式的担保责任，无论是承诺的还是暗含的，包括但不限于就适售性和为某个特殊目的的适用性的默认担保责任。有关本程序质量与效能的全部风险均由您承担。如本程序被证明有瑕疵，您应承担所有必要的服务、修复或更正的费用。 

@en @item Limitation of Liability.
@item 责任范围

@en IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
@en WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR
@en CONVEYS THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,
@en INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES
@en ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT
@en NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR
@en LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM
@en TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER
@en PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
除非受适用法律要求或者书面同意，任何版权所有者，或任何依前述方式修改和/或发布本程序者，对于您因为使用或不能使用本程序所造成的一般性、特殊性、意外性或间接性损失，不负任何责任（包括但不限于，资料损失，资料执行不精确，或应由您或第三人承担的损失，或本程序无法与其他程序运作等），即便该版权所有者或其他组织已经被告知程序有此类损失的可能性也是如此。 

@en @item Interpretation of Sections 15 and 16.
@item 第 15 和 16 节的解释 

@en If the disclaimer of warranty and limitation of liability provided
@en above cannot be given local legal effect according to their terms,
@en reviewing courts shall apply local law that most closely approximates
@en an absolute waiver of all civil liability in connection with the
@en Program, unless a warranty or assumption of liability accompanies a
@en copy of the Program in return for a fee.
如果上述免责申明和责任范围不能按照地方法律条款获得法律效力，复审法庭应该采用最接近于完全放弃关于本程序的民事责任的法律，除非随同本程序的责任担保或责任假设合同是收费的。 

@end enumerate

@en @heading END OF TERMS AND CONDITIONS
@heading 条款和条件结束

@en @heading How to Apply These Terms to Your New Programs
@heading 如何在您的新程序中应用这些条款

@en If you develop a new program, and you want it to be of the greatest
@en possible use to the public, the best way to achieve this is to make it
@en free software which everyone can redistribute and change under these
@en terms.
如果您开发了一个新程序，并且希望能够让它尽可能地被大众使用，达成此目的的最好方式就是让它成为自由软件。任何人都能够依据这些条款对该软件再次发布和修改。 

@en To do so, attach the following notices to the program.  It is safest
@en to attach them to the start of each source file to most effectively
@en state the exclusion of warranty; and each file should have at least
@en the ``copyright'' line and a pointer to where the full notice is found.
为了做到这一点，请将以下声明附加到程序上。最安全的作法，是将声明放在每份源码文件的起始处，以有效传达无担保责任的讯息；且每份文件至少应有「版权」列以及本份声明全文位置的提示。 

@smallexample
@en @var{one line to give the program's name and a brief idea of what it does.}  
@en Copyright (C) @var{year} @var{name of author}
@var{用一行描述程序的名称与其用途简述}  
版权所有 (C) @var{年份} @var{作者姓名}

@en This program is free software: you can redistribute it and/or modify
@en it under the terms of the GNU General Public License as published by
@en the Free Software Foundation, either version 3 of the License, or (at
@en your option) any later version.
本程序为自由软件；您可依据自由软件基金会所发表的GNU通用公共授权条款，对本程序再次发布和/或修改；无论您依据的是本授权的第三版，或（您可选的）任一日后发行的版本。 

@en This program is distributed in the hope that it will be useful, but
@en WITHOUT ANY WARRANTY; without even the implied warranty of
@en MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
@en General Public License for more details.
本程序是基于使用目的而加以发布，然而不负任何担保责任；亦无对适售性或特定目的适用性所为的默示性担保。详情请参照 GNU 通用公共授权。 

@en You should have received a copy of the GNU General Public License
@en along with this program.  If not, see @url{http://www.gnu.org/licenses/}.
@end smallexample
您应已收到附随于本程序的 GNU 通用公共授权的副本；如果没有，请参照 @url{http://www.gnu.org/licenses/} 。

@en Also add information on how to contact you by electronic and paper mail.
同时附上如何以电子及书面信件与您联系的资料。

@en If the program does terminal interaction, make it output a short
@en notice like this when it starts in an interactive mode:
如果程序进行终端交互方式运作，请在交互式模式开始时，输出以下提示：

@smallexample
@en @var{program} Copyright (C) @var{year} @var{name of author} 
@en This program comes with ABSOLUTELY NO WARRANTY; for details type @samp{show w}.
@en This is free software, and you are welcome to redistribute it
@en under certain conditions; type @samp{show c} for details.
@var{程序} 版权所有 (C) @var{年份} @var{作者姓名} 
本程序不负任何担保责任，欲知详情请输入 @samp{show w}。
这是一个自由软件，欢迎您在特定条件下再发布本程序；欲知详情请输入 @samp{show c}。
@end smallexample

@en The hypothetical commands @samp{show w} and @samp{show c} should show
@en the appropriate parts of the General Public License.  Of course, your
@en program's commands might be different; for a GUI interface, you would
@en use an ``about box''.
所假设的指令 @samp{show w} 与 @samp{show c} 应显示通用公共授权的相对应条款。当然，您可以使用其他的指令名称；对于图形用户界面，您可以用``关于''项代实现此功能。 

@en You should also get your employer (if you work as a programmer) or school,
@en if any, to sign a ``copyright disclaimer'' for the program, if necessary.
@en For more information on this, and how to apply and follow the GNU GPL, see
@en @url{http://www.gnu.org/licenses/}.
如有需要，您还应该取得您的雇主（若您的工作为程序设计师）或学校就本程序所签署的``版权放弃承诺书''。欲知这方面的详情，以及如何应用和遵守 GNU 通用公共授权，请参考 @url{http://www.gnu.org/licenses/}。

@en The GNU General Public License does not permit incorporating your
@en program into proprietary programs.  If your program is a subroutine
@en library, you may consider it more useful to permit linking proprietary
@en applications with the library.  If this is what you want to do, use
@en the GNU Lesser General Public License instead of this License.  But
@en first, please read @url{http://www.gnu.org/philosophy/why-not-lgpl.html}.
GNU 通用公共授权并不允许您将本程序合并到私有的程序中。若您的程序是一个子程序库，您可能认为允许私有的应用程序链接该库会更有用。如果这是您所想做的，请使用 GNU 松弛通用公共授权代替本授权。但这样做之前，请阅读 @url{http://www.gnu.org/philosophy/why-not-lgpl.html}。
@c man end
